name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint editorconfig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: editorconfig
      run: |
          docker run --rm --volume=$PWD:/check mstruebing/editorconfig-checker ec --exclude ".git|\.meta$|\.asset$|\.unity$|\.asmdef$|ProjectSettings"
